package config

var AwsFullRegionsList = []string{
	"af-south-1",     // Africa (Cape Town)
	"ap-east-1",      // Asia Pacific (Hong Kong)
	"ap-south-2",     // Asia Pacific (Hyderabad)
	"ap-southeast-3", // Asia Pacific (Jakarta)
	"ap-southeast-4", // Asia Pacific (Melbourne)
	"eu-central-2",   // Europe (Zurich)
	"eu-south-1",     // Europe (Milan)
	"eu-south-2",     // Europe (Spain)
	"il-central-1",   // Israel (Tel Aviv)
	"me-central-1",   // Middle East (UAE)
	"me-south-1",     // Middle East (Bahrain)
	"us-west-2",      // US West (Oregon)
	"us-west-1",      // US West (N. California)
	"us-east-2",      // US East (Ohio)
	"us-east-1",      // US East (N. Virginia)
	"sa-east-1",      // South America (São Paulo)
	"eu-west-3",      // Europe (Paris)
	"eu-west-2",      // Europe (London)
	"eu-west-1",      // Europe (Ireland)
	"eu-north-1",     // Europe (Stockholm)
	"eu-central-1",   // Europe (Frankfurt)
	"ca-central-1",   // Canada (Central)
	"ap-southeast-2", // Asia Pacific (Sydney)
	"ap-southeast-1", // Asia Pacific (Singapore)
	"ap-south-1",     // Asia Pacific (Mumbai)
	"ap-northeast-3", // Asia Pacific (Osaka)
	"ap-northeast-2", // Asia Pacific (Seoul)
}
